
    const correctCode = '1579';
    const obj = {
    es: {
      back: "Volver",
      title: "Córdoba 5579",
      subtitle: "Portal de Check-In Digital y Manual del Huésped",
      welcomeTitle: "¡Te damos la bienvenida!",
      welcomeText: "Hemos preparado esta guía personalizada para que tu ingreso sea autónomo, rápido y sin fricciones. Si tenés cualquier consulta, podés contactar a Jorge directamente por WhatsApp.",
      wifiTitle: "Conexión a Wi-Fi",
      wifiRed: "Red (SSID)",
      wifiPass: "Contraseña",
      wifiCopy: "Copiar",
      wifiCopied: "Copiado",
      wifiNote: "Las credenciales detalladas de conexión y el código QR de configuración rápida también se encuentran impresos en carteles enmarcados dentro del departamento.",
      manualTitle: "Manual de Ingreso Autónomo",
      videoLabel: "Video Guía",
      videoTitle: "Cómo ingresar al edificio y retirar las llaves",
      step1Title: "1. Llegada al Edificio",
      step1Desc: "Dirigite a la entrada principal en Av. Córdoba 5579. El ingreso cuenta con excelente iluminación y cámaras de seguridad las 24 hs.",
      step2Title: "2. Retiro de Llaves (Lockbox)",
      step2Desc: "A la derecha de la puerta de entrada exterior verás las cajas metálicas de seguridad. Ubicá la rotulada como \"Depto 101\". Ingresá el código de combinación que te indicamos previamente por mensaje de confirmación, deslizá la traba hacia abajo y retirá el juego de llaves.",
      step3Title: "3. Llavero Magnético en Entrada Exterior",
      step3Desc: "Aproximá el llavero magnético circular (azul o negro) al lector electromagnético del ingreso exterior para abrir la puerta de vidrio del hall. Dirigite a los ascensores o escaleras y subí al piso 1.",
      step4Title: "4. Acceso al Departamento 101",
      step4Desc: "El departamento es el 101 (piso 1). Introduce la llave física en la cerradura, girala dos vueltas a la izquierda ¡y bienvenido a tu departamento de diseño!",
      rulesTitle: "Normas Clave de Convivencia",
      ruleSmoke: "Prohibido fumar:",
      ruleSmokeText: "Multa estricta por fumar dentro del departamento o pasillos del edificio.",
      rulePets: "Sin mascotas:",
      rulePetsText: "No se admite el ingreso de mascotas en la propiedad en ningún caso.",
      ruleSilence: "Horas de silencio:",
      ruleSilenceText: "De 22:00 a 08:00 hs. Respetar el descanso de los vecinos del edificio.",
      rulePool: "Piscina en terraza:",
      rulePoolText: "Piso 9. Exclusivo huéspedes, ducha obligatoria previa. Cierre 20 hs.",
      checkoutTitle: "Instrucciones de Check-Out",
      checkoutIntro: "El horario límite de check-out es a las 11:00 hs. Te solicitamos:",
      checkout1: "Apagar luces y aires: Asegurate de apagar todos los aires acondicionados y luces.",
      checkout2: "Guardar llaves: Cerrá la puerta del departamento tirando firmemente y colocá las llaves de regreso en la misma caja de seguridad (lockbox) del ingreso exterior, desordenando la combinación al cerrarla.",
      checkout3: "Avisar por WhatsApp: Enviale un mensaje rápido a Jorge confirmando tu salida. ¡Buen viaje de regreso!",
      lockboxSimulatorTitle: "Simulador de Lockbox Interactivo",
      lockboxInstruction: `Desliza para elegir los números. Prueba la combinación demo '${correctCode}' y desliza la traba negra lateral hacia abajo. El código real del departamento te llegará por mensaje privado.`,
      lockboxLocked: `🔒 Cerrado - Prueba la clave demo '${correctCode}'`,
      lockboxUnlocked: "🔓 ¡Abierto! Retira tus llaves de prueba.",
      emergencyTitle: "Teléfonos de Emergencia",
      emergency911Desc: "Policía y Emergencias Generales",
      emergency107Desc: "SAME (Urgencias Médicas)",
      emergency100Desc: "Bomberos",
      emergency103Desc: "Defensa Civil",
      emergencyHostDesc: "Jorge (Anfitrión - Urgencias Depto)",
      mapOpenBtn: "Abrir Ubicación en Mapas ↗"
    },
    en: {
      back: "Back",
      title: "Cordoba 5579",
      subtitle: "Digital Check-In Portal & Guest Manual",
      welcomeTitle: "Welcome!",
      welcomeText: "We have prepared this personalized guide for a self-guided, quick, and smooth check-in. If you have any questions, you can contact Jorge directly via WhatsApp.",
      wifiTitle: "Wi-Fi Connection",
      wifiRed: "Network (SSID)",
      wifiPass: "Password",
      wifiCopy: "Copy",
      wifiCopied: "Copied",
      wifiNote: "Detailed connection credentials and a quick setup QR code are also printed on framed signs inside the apartment.",
      manualTitle: "Self-Check-In Manual",
      videoLabel: "Video Guide",
      videoTitle: "How to enter the building and retrieve the keys",
      step1Title: "1. Arrival at the Building",
      step1Desc: "Go to the main entrance at Av. Cordoba 5579. The entrance is well-lit and secured with security cameras 24/7.",
      step2Title: "2. Retrieve Keys (Lockbox)",
      step2Desc: "To the right of the outer entrance door, you will see the metal security lockboxes. Find the one labeled \"Depto 101\". Enter the combination code sent to you previously via confirmation message, slide the latch down, and retrieve the set of keys.",
      step3Title: "3. Magnetic Tag at Outer Entrance",
      step3Desc: "Hold the circular magnetic key tag (blue or black) close to the electromagnetic reader at the outer entrance to unlock the glass lobby door. Go to the elevators or stairs and go up to the 1st floor.",
      step4Title: "4. Access Apartment 101",
      step4Desc: "The apartment is 101 (1st floor). Insert the physical key into the lock, turn it twice to the left, and welcome to your design apartment!",
      rulesTitle: "Key House Rules",
      ruleSmoke: "No smoking:",
      ruleSmokeText: "Strict fee for smoking inside the apartment or building hallways.",
      rulePets: "No pets:",
      rulePetsText: "Pets are not allowed on the property under any circumstances.",
      ruleSilence: "Quiet hours:",
      ruleSilenceText: "From 10:00 PM to 8:00 AM. Please respect the rest of the neighbors.",
      rulePool: "Rooftop Pool:",
      rulePoolText: "9th floor. Guests only, shower required before entering. Closes at 8 PM.",
      checkoutTitle: "Check-Out Instructions",
      checkoutIntro: "Check-out time is strictly by 11:00 AM. We kindly request that you:",
      checkout1: "Turn off lights and AC: Make sure all air conditioning units and lights are turned off.",
      checkout2: "Return keys: Close the apartment door firmly behind you and return the keys to the same security lockbox at the outer entrance, scrambling the code wheels after closing it.",
      checkout3: "Notify via WhatsApp: Send a quick message to Jorge confirming your departure. Have a safe trip back!",
      lockboxSimulatorTitle: "Interactive Lockbox Simulator",
      lockboxInstruction: `Scroll to choose numbers. Try the demo combination '${correctCode}' and slide the black latch downwards. The real code will be sent privately.`,
      lockboxLocked: `🔒 Locked - Try demo code '${correctCode}'`,
      lockboxUnlocked: "🔓 Opened! Retrieve your test keys.",
      emergencyTitle: "Emergency Contacts",
      emergency911Desc: "Police & General Emergencies",
      emergency107Desc: "SAME (Medical Emergencies)",
      emergency100Desc: "Fire Department",
      emergency103Desc: "Civil Defense",
      emergencyHostDesc: "Jorge (Host - Apartment Urgencies)",
      mapOpenBtn: "Open Location in Maps ↗"
    }
  };
    const fs = require('fs');
    fs.writeFileSync('scratch/checkin_es.json', JSON.stringify(obj.es, null, 2));
    fs.writeFileSync('scratch/checkin_en.json', JSON.stringify(obj.en, null, 2));
    